package chatuniformconeccion;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author franco
 */
public class AddFriend extends javax.swing.JFrame {

    /**
     * Creates new form AddFriend
     */
    private Statement st;
    private String usuario = "";
    private ResultSet rs = null;
    private Connection conexion = null;

    public AddFriend(String usuario, Connection conexion) {

        initComponents();
        this.conexion = conexion;
        this.usuario = usuario;
        try {
            st = conexion.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(IconsForm.class.getName()).log(Level.SEVERE, null, ex);
        }




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNick = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar amigo");

        jLabel1.setText("Ingrese el nick:");

        txtNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNickActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        lblResultado.setText("Apriete para buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblResultado)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNickActionPerformed
        String nick = txtNick.getText();
        if (nick.equals(usuario)) {
            lblResultado.setText("No puedes agregarte a ti mismo..");
        } else {
            String query = "SELECT * FROM webchat_users WHERE name = '" + nick + "'";
            boolean yaUsado = false;
            try {
                rs = st.executeQuery(query);
            } catch (SQLException ex) {
                Logger.getLogger(AddFriend.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                if (!rs.next()) {
                    lblResultado.setText("No se encuentra el usuario");

                } else {
                    boolean yaAmigo = false;
                    query = "SELECT * FROM webchat_users WHERE name = '" + usuario + "'";

                    try {
                        rs = st.executeQuery(query);
                    } catch (SQLException ex) {
                        Logger.getLogger(Graficos.class.getName()).log(Level.SEVERE, null, ex);
                        System.out.println("no se hizo la segunda ");
                    }


                    rs.next();
                    String amigos = rs.getString("friends");
                    if (amigos != null && !amigos.equals("")) {
                        String[] arrayAmigos1 = amigos.split(", ");
                        for (int i = 0; i < arrayAmigos1.length; i++) {
                            if (arrayAmigos1[i].equals(nick)) {
                                yaAmigo = true;
                                break;
                            }
                        }
                    }

                    if (yaAmigo) {
                        lblResultado.setText("Ya tienes como contacto a ese usuario");
                    } else {
                        query = "SELECT * FROM webchat_users WHERE name = '" + usuario + "'";

                        try {
                            rs = st.executeQuery(query);
                        } catch (SQLException ex) {
                            Logger.getLogger(AddFriend.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try {
                            if (rs.next()) {

                                String amigosrq = rs.getString("friendsrq");

                                if (amigosrq != null && !amigosrq.equals("")) {
                                    String[] arrayAmigos = amigosrq.split(", ");
                                    
                                    for (int i = 0; i < arrayAmigos.length; i++) {
                                        
                                        if (arrayAmigos[i].equals(nick)) {
                                            yaUsado = true;
                                           
                                            break;

                                        }
                                    }
                                    if (yaUsado) {
                                        System.out.println("ya1");
                                        lblResultado.setText("Ya enviaste esa solicitud de contacto a " + nick);
                                    } else {
                                        amigosrq += ", " + nick;
                                        System.out.println("enviado1");
                                        st.executeUpdate("UPDATE webchat_users SET friendsrq='" + amigosrq + "' WHERE name='" + usuario + "'");
                                        lblResultado.setText("Se envio solicitud de contacto a " + nick);
                                    }
                                } else {
                                    amigosrq = nick;
                                    System.out.println("enviado2");
                                    st.executeUpdate("UPDATE webchat_users SET friendsrq='" + amigosrq + "' WHERE name='" + usuario + "'");
                                    lblResultado.setText("Se envio solicitud de contacto a " + nick);
                                }


                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(Graficos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        query = "SELECT * FROM webchat_users WHERE name = '" + nick + "'";

                        try {
                            rs = st.executeQuery(query);
                        } catch (SQLException ex) {
                            Logger.getLogger(AddFriend.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        yaUsado = false;
                        try {
                            if (rs.next()) {

                                String amigosrqr = rs.getString("friendsrqr");
                                //System.out.println(amigosrqr);
                                if (amigosrqr != null && !amigosrqr.equals("")) {
                                    String[] arrayAmigos = amigosrqr.split(", ");
                                    for (int i = 0; i < arrayAmigos.length; i++) {
                                        //System.out.println("\n"+arrayAmigos[i]);
                                        if (arrayAmigos[i].equals(usuario)) {
                                            yaUsado = true;
                                            System.out.println("verdadero");
                                            break;
                                        }
                                    }
                                    if (yaUsado) {
                                        System.out.println("ya2");
                                        lblResultado.setText("Ya enviaste esa solicitud de contacto a " + nick);
                                    } else {
                                        amigosrqr += ", " + usuario;
                                        System.out.println("enviado3");
                                        st.executeUpdate("UPDATE webchat_users SET friendsrqr='" + amigosrqr + "' WHERE name='" + nick + "'");
                                        lblResultado.setText("Se envio solicitud de contacto a " + nick);
                                    }
                                } else {
                                    amigosrqr = usuario;
                                    System.out.println("enviado4");
                                    st.executeUpdate("UPDATE webchat_users SET friendsrqr='" + amigosrqr + "' WHERE name='" + nick + "'");
                                    lblResultado.setText("Se envio solicitud de contacto a " + nick);
                                }
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(Graficos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(Graficos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtNickActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nick = txtNick.getText();
        if (nick.equals(usuario)) {
            lblResultado.setText("No puedes agregarte a ti mismo..");
        } else {
            String query = "SELECT * FROM webchat_users WHERE name = '" + nick + "'";
            boolean yaUsado = false;
            try {
                rs = st.executeQuery(query);
            } catch (SQLException ex) {
                Logger.getLogger(AddFriend.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                if (!rs.next()) {
                    lblResultado.setText("No se encuentra el usuario");

                } else {
                    boolean yaAmigo = false;
                    query = "SELECT * FROM webchat_users WHERE name = '" + usuario + "'";

                    try {
                        rs = st.executeQuery(query);
                    } catch (SQLException ex) {
                        Logger.getLogger(Graficos.class.getName()).log(Level.SEVERE, null, ex);
                        System.out.println("no se hizo la segunda ");
                    }


                    rs.next();
                    String amigos = rs.getString("friends");
                    if (amigos != null && !amigos.equals("")) {
                        String[] arrayAmigos1 = amigos.split(", ");
                        for (int i = 0; i < arrayAmigos1.length; i++) {
                            if (arrayAmigos1[i].equals(nick)) {
                                yaAmigo = true;
                                break;
                            }
                        }
                    }

                    if (yaAmigo) {
                        lblResultado.setText("Ya tienes como contacto a ese usuario");
                    } else {
                        query = "SELECT * FROM webchat_users WHERE name = '" + usuario + "'";

                        try {
                            rs = st.executeQuery(query);
                        } catch (SQLException ex) {
                            Logger.getLogger(AddFriend.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try {
                            if (rs.next()) {

                                String amigosrq = rs.getString("friendsrq");

                                if (amigosrq != null && !amigosrq.equals("")) {
                                    String[] arrayAmigos = amigosrq.split(", ");
                                    
                                    for (int i = 0; i < arrayAmigos.length; i++) {
                                        
                                        if (arrayAmigos[i].equals(nick)) {
                                            yaUsado = true;
                                           
                                            break;

                                        }
                                    }
                                    if (yaUsado) {
                                        System.out.println("ya1");
                                        lblResultado.setText("Ya enviaste esa solicitud de contacto a " + nick);
                                    } else {
                                        amigosrq += ", " + nick;
                                        System.out.println("enviado1");
                                        st.executeUpdate("UPDATE webchat_users SET friendsrq='" + amigosrq + "' WHERE name='" + usuario + "'");
                                        lblResultado.setText("Se envio solicitud de contacto a " + nick);
                                    }
                                } else {
                                    amigosrq = nick;
                                    System.out.println("enviado2");
                                    st.executeUpdate("UPDATE webchat_users SET friendsrq='" + amigosrq + "' WHERE name='" + usuario + "'");
                                    lblResultado.setText("Se envio solicitud de contacto a " + nick);
                                }


                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(Graficos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        query = "SELECT * FROM webchat_users WHERE name = '" + nick + "'";

                        try {
                            rs = st.executeQuery(query);
                        } catch (SQLException ex) {
                            Logger.getLogger(AddFriend.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        yaUsado = false;
                        try {
                            if (rs.next()) {

                                String amigosrqr = rs.getString("friendsrqr");
                                //System.out.println(amigosrqr);
                                if (amigosrqr != null && !amigosrqr.equals("")) {
                                    String[] arrayAmigos = amigosrqr.split(", ");
                                    for (int i = 0; i < arrayAmigos.length; i++) {
                                        //System.out.println("\n"+arrayAmigos[i]);
                                        if (arrayAmigos[i].equals(usuario)) {
                                            yaUsado = true;
                                            System.out.println("verdadero");
                                            break;
                                        }
                                    }
                                    if (yaUsado) {
                                        System.out.println("ya2");
                                        lblResultado.setText("Ya enviaste esa solicitud de contacto a " + nick);
                                    } else {
                                        amigosrqr += ", " + usuario;
                                        System.out.println("enviado3");
                                        st.executeUpdate("UPDATE webchat_users SET friendsrqr='" + amigosrqr + "' WHERE name='" + nick + "'");
                                        lblResultado.setText("Se envio solicitud de contacto a " + nick);
                                    }
                                } else {
                                    amigosrqr = usuario;
                                    System.out.println("enviado4");
                                    st.executeUpdate("UPDATE webchat_users SET friendsrqr='" + amigosrqr + "' WHERE name='" + nick + "'");
                                    lblResultado.setText("Se envio solicitud de contacto a " + nick);
                                }


                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(Graficos.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(Graficos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    @Override
    public void dispose() {
        try {
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(AddFriend.class.getName()).log(Level.SEVERE, null, ex);
        }
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtNick;
    // End of variables declaration//GEN-END:variables
}
